name: Build WinUI App

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: "GTA Journal.sln"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore NuGet packages
        run: 'dotnet restore "GTA Journal.sln"'

      - name: Build the project
        run: 'dotnet build "GTA Journal/GTA Journal.csproj" -c Release -p:Platform=x64'

      - name: Build the updater
        run: 'dotnet build "GTA Journal Updater/GTA Journal Updater.csproj" -c Release -p:Platform=x64'

      - name: Publish the application
        run: 'dotnet publish "GTA Journal/GTA Journal.csproj" -c Release -p:Platform=x64 --output ./output'

      # Проверить!
      - name: Download Inno Setup
        run: Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile "InnoSetup.exe"

      - name: Install Inno Setup
        run: Start-Process -FilePath "InnoSetup.exe" -ArgumentList "/VERYSILENT" -Wait

      - name: Create Installer
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" setup.iss

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WinUI-App-Installer
          path: ./GTAJournalInstaller.exe
