name: Build WinUI App

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  packages: write
  contents: write

jobs:
  build:
    strategy:
      matrix:
        platform: [x86, x64]

    runs-on: windows-latest

    env:
      Solution_Name: "GTA Journal.sln"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore NuGet packages
        run: 'dotnet restore "GTA Journal.sln"'

      - name: Build the project
        run: 'dotnet build "GTA Journal/GTA Journal.csproj" -c Release -p:Platform=$env:Platform'
        env:
          Platform: ${{ matrix.platform }}

      - name: Build the updater
        run: 'dotnet build "GTA Journal Updater/GTA Journal Updater.csproj" -c Release -p:Platform=$env:Platform'
        env:
          Platform: ${{ matrix.platform }}

      - name: Publish the application
        run: 'dotnet publish "GTA Journal/GTA Journal.csproj" -c Release -p:Platform=$env:Platform --output ./output'
        env:
          Platform: ${{ matrix.platform }}

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
        with:
          path: setup.iss
          options: /O+

      - name: Collect app version
        id: appversion
        run: |
          .\getversion.ps1 >> $GITHUB_OUTPUT

      - name: Rename installer
        env:
          Platform: ${{ matrix.platform }}
        run: |
          Rename-Item "GTAJournalInstaller.exe" -NewName "Setup ($env:Platform).exe”

      - name: Upload GitHub release
        id: ghupl
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          tag_name: ${{ steps.appversion.outputs.version }}
          files: Setup (${{ matrix.platform }}).exe
